<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>True</UseWindowsForms>
    <ApplicationIcon>bin\Debug\net8.0-windows\icon.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="bin\Debug\net8.0-windows\icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Emgu.CV" Version="4.9.0.5494" />
    <PackageReference Include="Emgu.CV.Bitmap" Version="4.9.0.5494" />
    <PackageReference Include="Emgu.CV.runtime.windows" Version="4.9.0.5494" />
    <PackageReference Include="Serilog" Version="4.0.0" />
    <PackageReference Include="Serilog.Sinks.RichTextBox.Wpf" Version="1.1.0" />
    <PackageReference Include="System.IO.Ports" Version="8.0.0" />
    <PackageReference Include="TaskScheduler" Version="2.11.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AppDomain\AppDomain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Models\" />
    <Folder Include="Resources\" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="openalpr-net">
      <HintPath>..\MlNetOnnxAlpr.OpenAlprClient\Dependencies\openalpr-net.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="ComPortPairForm.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="LprServicesControl.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="LprReaderControl.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="ComPortsControl.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

</Project>
